# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. Current version: 0.0.6
class Halptask < Formula
  desc "A high-performance keyboard-driven TUI bullet point outliner and task manager"
  homepage "https://github.com/arkalon76/halptask"
  version "0.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arkalon76/halptask/releases/download/v0.0.6/halptask_Darwin_x86_64.tar.gz"
      sha256 "a362f859fc084bf8f48c4221142f36b49a51369313d87048bb28070285d8c0d8"

      def install
        bin.install "halptask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arkalon76/halptask/releases/download/v0.0.6/halptask_Darwin_arm64.tar.gz"
      sha256 "e70d900bef3d1ed4d7f3f615006c861c20deb4fe90d696a0921bdb45cbc4af08"

      def install
        bin.install "halptask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/arkalon76/halptask/releases/download/v0.0.6/halptask_Linux_x86_64.tar.gz"
      sha256 "279b95f38bfaa7490836a6d41d67e092ac3ee02474a951c8f67cab31653f061b"

      def install
        bin.install "halptask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arkalon76/halptask/releases/download/v0.0.6/halptask_Linux_arm64.tar.gz"
      sha256 "d6a5426b5551f4c87e546d895a0f1ad9a39dac36887d87ece4db34d23a940655"

      def install
        bin.install "halptask"
      end
    end
  end
end
